# Generated by Django 5.1 on 2024-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrandoPontosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('horarios', models.CharField(max_length=255, verbose_name='Horários')),
            ],
        ),
    ]
