# Generated by Django 5.1 on 2024-08-24 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrandopontosturisticos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrandopontosturisticos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
